name: Deploy React App with Docker

on:
  push:
    branches:
      - main
      - dev
      - test
      - stag

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # Step 3: Install Dependencies and Build App
    - name: Install Dependencies and Build App
      run: |
        npm install
        npm run build

    # Step 4: Build Docker Image
    - name: Build Docker Image
      env:
        BRANCH: ${{ github.ref_name }}
      run: |
        docker build -t my-react-app:${{ github.ref_name }} .

    # Step 5: Log in to Docker Hub (or container registry)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 6: Push Docker Image
    - name: Push Docker Image
      env:
        BRANCH: ${{ github.ref_name }}
      run: |
        docker tag my-react-app:${{ github.ref_name }} ${{ secrets.DOCKER_USERNAME }}/my-react-app:${{ github.ref_name }}
        docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app:${{ github.ref_name }}

    # Step 7: Deploy to EC2
    - name: Deploy Docker Container to EC2
      env:
        BRANCH: ${{ github.ref_name }}
        EC2_USER: ubuntu
        EC2_HOST: ${{ secrets.EC2_HOST }}
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
      run: |
        # Write the private key to a temporary file
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        # Ensure the .ssh directory exists
        mkdir -p ~/.ssh

        # Add EC2 host to known_hosts to avoid host key verification failure
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

        # Install Docker if not present, log in, and deploy
        ssh -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          # Install Docker if not already installed
          if ! command -v docker &> /dev/null; then
            echo "Docker not found. Installing Docker..."
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          fi

          # Add user to Docker group to avoid permission issues
          if ! groups $USER | grep -q docker; then
            sudo usermod -aG docker $USER
          fi

          # Determine the port based on the branch
          BRANCH=${BRANCH:-"main"}  # Default to "main" if BRANCH is not set
          case "$BRANCH" in
            main) PORT=5173 ;;
            dev) PORT=5174 ;;
            test) PORT=5175 ;;
            stag) PORT=5176 ;;
            *) PORT=5173 ;;  # Default to port 5173 for unrecognized branches
          esac

          # Stop any process using the specified port
          if lsof -i:$PORT | grep LISTEN; then
            echo "Port $PORT is in use. Stopping the process..."
            sudo fuser -k $PORT/tcp || true
          fi

          # Log in to Docker Hub and deploy
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-react-app:$BRANCH
          
          # Stop and remove any existing container with the same name
          sudo docker stop my-react-app-$BRANCH || true
          sudo docker rm my-react-app-$BRANCH || true

          # Run the new container
          sudo docker run -d --name my-react-app-$BRANCH -p $PORT:80 ${{ secrets.DOCKER_USERNAME }}/my-react-app:$BRANCH
        EOF

        # Cleanup the private key
        rm private_key.pem
